### PR TITLE
Added Pkcs12/PFX Certificate and Write-Progress

### PR DESCRIPTION
**Pull request by ChrisLynchHPE**
* Added Pkcs12/PFX Support to main module scripts by adding CertPath and CertPassphrase parameters.
* Added Pkcs12/PFC Certificate validation to New-RabbitMqSslOption.
* Added Write-Porgress support to Wait-RabbitMqMessage, Start-RabbitMqListener, Net-RabbitMqConnectionFactory and Connect-RabbitMqChannel.
* Updated RabbitMQ.Client.dll to v3.6.5.

Unfortunately, I don't have a way to test Credential support, as the RabbitMQ service we use requires certificate authentication.  I have yet to update your Pester test script with a framework that validates this.  So all testing has been performed manually.

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hi!

Yay PKI : )  Will take a peak at this, might not be until this weekend - @gpduck @gaelcolas any concerns?

Cheers!

**Comment by ChrisLynchHPE** [comment]
It took a while.  I really wish the Pivitol team would fix their bug with Uri and uri public properties in their RabbitMQ.Client library.  Would have made this a lot easier.

I would like to help clean up the code, like add parameter sets to each parameter, so they are declared correctly, and not stepping over each other.

**Comment by gaelcolas** [comment]
I love the idea! Thanks @ChrisLynchHPE for submitting!

I'll look at this in more details tomorrow.

I agree that we'll probably need some parameter sets.

For (simple) integration testing on my Windows 10 machine, I now use a linux docker container with rabbitmq, which I recommend!
`docker run -d --name rabbitmq -p 5671:5671 -p 5672:5672 -p 15671:15671 -p 15672:15672 -p 25672:25672 rabbitmq:3-management`

**Comment by ChrisLynchHPE** [comment]
I am standing up a Windows Server 2016 Docker system to do some additional testing next week.  Any update on this pull request?

**Comment by RamblingCookieMonster** [comment]
Hi!

A few quick thoughts if they make sense:

* I like progress indicators, but an option to suppress progress might be handy
* In New-RabbitMqConnectionFactory.ps1, the factories port is set to 5671 - just curious about what this is; needed for the new props? Explicitly indicate port vs. using default?  Something else?

Looks good to me, I'd be up for merging this in and tackling a switch to avoid the progress bar later.  I'll defer to @gpduck and @gaelcolas in case they have other concerns : )

Cheers!

**Comment by gpduck** [comment]
I'm also curious about why we roll the default TLS from 1.2 down to 1.1?

**Comment by gpduck** [comment]
RE: Progress bar

Is $ProgressPreference enough for suppression?  How do other projects handle it?  I don't recall noticing other cmdlets with a parameter to turn off progress bars (but I don't see that many things with progress bars either).

**Comment by ChrisLynchHPE** [comment]
I disagree about progress bars.  It takes almost 5-7 seconds to initiate a connection to the SCMB and nothing is worse than seeing a blinking cursor that you have no idea what's going on.  I have never seen an option to suppress Write-Progress in Cmdlets, and I certainly do not have that option in my Cmdlets I develop.

Setting the Factory Port to 5671 is just setting a default value.  A user can overload it with their own parameter value if they choose.  If SCMB listens on the default 5671, why wouldn't you have a default value?

**Comment by ChrisLynchHPE** [comment]
@gpduck, Write-Progress is just a good thing to do.  Users want to know how things are progressing.  As I stated above, I have never seen anyone have an option to suppress the output of Write-Progress.  Well, only when say someone is wanting to use Write-Verbose or Write-Debug, the output can become quite "interesting".

**Comment by ChrisLynchHPE** [comment]
As for the "downgrade" of TLS from 1.2 to 1.1, that was an error on my part.  I was testing with my own product to make sure TLS 1.1 and 1.2 were working fine, and forgot to update it back to TLS12.  If you want, I can do another PR with that updated, or after merge one of you can.  Just let me know how you'd want that fixed.

**Comment by RamblingCookieMonster** [comment]
Sounds good on the progress bit @ChrisLynchHPE, I'd agree with @gpduck, good as is, if folks really want to suppress it, they can use $ProgressPreference, no need worrying about adding extra code/parameters.

Cheers!

**Pull request merged**
