### PR TITLE
Change manifest and main module file names cases

### PR DESCRIPTION
**Pull request by yuvalmarciano**
From Powershell 7 engine's code:
image

Therefore, we need the module dir name and the inner manifest file name to be defined using the same case. Before this change, I couldn't import `PSRabbitMq` on Linux (Debian 10), on which the case matters.

@RamblingCookieMonster Let's please create a new release after this fix is merged.
Thanks!!

### CODE REVIEW

**Comment by yuvalmarciano** [comment]
@RamblingCookieMonster Can we merge it please? 🙂

**Comment by yogevyuval** [comment]
This is a life saver! thanks for the fix. Waiting for a new version :)

**Comment by yuvalmarciano** [comment]
@RamblingCookieMonster ?

**Comment by RamblingCookieMonster** [comment]
Oy, thanks for the reminders, sorry all!  Let's see if the build process still works...

**Comment by yuvalmarciano** [comment]
@RamblingCookieMonster I can see 0.3.5 is released now, thanks! That's extremely helpful for me.

**Pull request merged**
