### PR TITLE
Feature/queue arguments

### PR DESCRIPTION
**Pull request by yuvalmarciano**
Add option to pass $Arguments as a dictionary to set queue arguments

### CODE REVIEW

**Comment by yuvalmarciano** [comment]
?

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Does this work as expected with and without arguments specified?  If so happy to merge (not using rabbitmq at the moment, so not something I can quickly validate)

**Comment by yuvalmarciano** [comment]
> Hiyo! Does this work as expected with and without $Arguments specified? If so happy to merge (not using rabbitmq at the moment, so not something I can quickly validate)

Yes I have checked it actually. Also - the default value of arguments is `$null`, and it's equivalent to the value before my PR :)

Thanks!!

**Comment by RamblingCookieMonster** [comment]
Works for me then, thanks!

**Comment by yuvalmarciano** [comment]
Hey @RamblingCookieMonster , could you please review my other PR https://github.com/RamblingCookieMonster/PSRabbitMq/pull/32 ?
Thanks in advance. Sorry for addressing you here, I don't have any other way 😅

**Pull request merged**
