### PR TITLE
Add -vhost parameter for other RabbitMQ Calls

### LINKED ISSUE #12: Some RabbitMQ calls dont support -vhost flag
There are about 3 functions that dont support specifying the -vhost flag. Adding them...

### PR DESCRIPTION
**Pull request by derekmwright**
Fixes #12

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hi!

Makes sense to me.  I'm assuming the default is `/` even if it's not specified (i.e. this wouldn't change behavior of existing scripts using the module)

@gpduck @gaelcolas, any concerns?  Also, I ping you because you created this (Chris) and seem active (Gael) - hit me up if you'd prefer I don't : )

Cheers!

**Comment by derekmwright** [comment]
Correct, parameter default is "/" to keep previous behavior

**Comment by gaelcolas** [comment]
Looks good to me. :)

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks Derek and Gael!  Merging

**Pull request merged**
